[build]
builder = "NIXPACKS"
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "npm run preview"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
port = 4173

[healthcheck]
path = "/"
timeout = 100